/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_donnée;

import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DELL 6440
 */
public class founisseur extends javax.swing.JFrame {

    ResultSet rs;
    BDD db;

    String codepro, nompro, hak;
    int old, dec, now;
    private static Pattern motif = null;
    private static Pattern motif1 = null;
    Matcher matcher, matcher1, matcher2;

    /**
     * Creates new form founisseur
     */
    public founisseur() {
        db = new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
    }

    public void table() {
        String a[] = { "nom_produit", "nom_founisseur", "quantite", "prix_unitaire"};
        rs = db.querySelect(a, "founisseur");
        table_pro.setModel(new ResultSetTableModel(rs));
    }

    void actualiser() {
        txt_no.setText("");
        txt_fo.setText("");
        txt_pri.setText("");
        txt_rech.setText("");
        com_rech.setSelectedItem("choix_categorie");
        com_rech1.setSelectedItem("choix_action");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pro = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        txt_rech = new javax.swing.JTextField();
        com_rech = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_fo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_pri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        com_rech1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 0));
        setLocation(new java.awt.Point(290, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        table_pro.setBackground(new java.awt.Color(204, 153, 0));
        table_pro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "nom_produit", "fournisseur", "quantite", "prix_vente", "stock sortie", "prix d'achat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_proMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 293));

        jButton6.setBackground(new java.awt.Color(0, 255, 153));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setText("Rechercher:");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txt_rech.setFont(new java.awt.Font("Minion Pro Cond", 0, 14)); // NOI18N
        txt_rech.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        com_rech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com_rech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choix_categorie", "nom_produit", "fournisseur" }));
        com_rech.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 153), 3, true));
        com_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_rechActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("prix unitaire:");

        txt_no.setFont(new java.awt.Font("Minion Pro Cond", 0, 14)); // NOI18N
        txt_no.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("nom_produit:");

        txt_fo.setFont(new java.awt.Font("Minion Pro Cond", 0, 14)); // NOI18N
        txt_fo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_fo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_foActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("fournisseur:");

        txt_pri.setFont(new java.awt.Font("Minion Pro Cond", 0, 14)); // NOI18N
        txt_pri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Rechercher par catégorie:");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Valider");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 255, 153));
        jButton7.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setText("Retour");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 3, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        label1.setBackground(new java.awt.Color(255, 51, 51));
        label1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("Quelle action:");

        com_rech1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com_rech1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choix_action", "ajout_prix_achat", "calcul_benefice" }));
        com_rech1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 153), 3, true));
        com_rech1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_rech1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(com_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(com_rech1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_no, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_rech))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_fo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pri, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_rech1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // bouton recherche
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (txt_rech.getText().equals("") || com_rech.getSelectedItem().equals("choix_categorie"))//si le textfield de recherche est vide le programme affichera "SVP entrer quelque chose"
        {
            JOptionPane.showMessageDialog(this, "SVP entrer quelques chose et selectionnez une categorie");
        } else if (com_rech.getSelectedItem().equals("nom_produit")) {
            //rs = db.querySelectAll("founisseur", "nom_produit LIKE '%" + txt_rech.getText() + "%'");
            rs=  db.exécutionQuery(" SELECT  nom_produit, nom_founisseur,quantite, prix_unitaire FROM founisseur WHERE nom_produit like '%"+ txt_rech.getText()+"%' ");
            //rs=db.exécutionQuery("select * from produit where username='"+txt_rech.getText()+"'");
            table_pro.setModel(new ResultSetTableModel(rs));
        } else if (com_rech.getSelectedItem().equals("fournisseur")) {
            //rs = db.querySelectAll("founisseur", "nom_founisseur LIKE '%" + txt_rech.getText() + "%'");
            rs=  db.exécutionQuery(" SELECT  nom_produit, nom_founisseur,quantite, prix_unitaire FROM founisseur WHERE nom_founisseur like '%"+ txt_rech.getText()+"%' ");
            table_pro.setModel(new ResultSetTableModel(rs));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noActionPerformed

    private void txt_foActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_foActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_foActionPerformed

    private void txt_priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priActionPerformed

    // bouton valider
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        motif = Pattern.compile("[0-9]*");
//        String id=String.valueOf(txt_rem.getText());
//        matcher1= motif.matcher(id);
//        String add=String.valueOf(txt_sto.getText());
//        matcher= motif.matcher(add);
        String ad = String.valueOf(txt_pri.getText());
        matcher2 = motif.matcher(ad);
        if (txt_no.getText().equals("") || txt_fo.getText().equals("")
                || txt_pri.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complètes dans tous les champs!");
        } else if (!(matcher2.matches())) {
            JOptionPane.showMessageDialog(this, "SVP entrer les chiffres pour les champs prix  et stock!");
        } else {

            if (com_rech1.getSelectedItem().equals("ajout_prix_achat")) {
                rs = db.exécutionQuery("select nom_produit, nom_founisseur from founisseur ");
                System.out.print(rs);
                try {
                    rs.beforeFirst();
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    while (rs.next()) {
                        codepro = rs.getString("nom_produit");
                        nompro = rs.getString("nom_founisseur");
                        //hak=rs.getString("fonction");
                        //System.out.print(username1);
                        if (txt_no.getText().equals(codepro) && txt_fo.getText().equals(nompro)) {
                            dec = Integer.parseInt(txt_pri.getText());
                            //now=old+dec;
                            //String nvstock = Integer.toString(now);
                            String nwqte = Integer.toString(dec);
                            // String a=String.valueOf(nvstock);
                            String aqt = String.valueOf(nwqte);
                            String[] colon = {"stock"};
                            // String [] isi={a};
                            String[] col = {"prix_unitaire"};
                            String[] aa = {aqt};
                            // System.out.println(db.queryUpdate("produit", colon, isi,"code_produit = '" +txt_co.getText()+"'" ));
                            System.out.println(db.queryUpdate("founisseur", col, aa, " nom_produit='" + txt_no.getText() + "' && nom_founisseur = '" + txt_fo.getText() + "'"));
                            table();
                            actualiser();
                        }
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                actualiser();
                label1.setText(String.valueOf(""));
            }
            if (com_rech1.getSelectedItem().equals("calcul_benefice")) {

                //JLabel jNom = new JLabel("Nom de la caisse : ");
                JLabel jMoi = new JLabel("Entrez le mois : ");
                JLabel jAne = new JLabel("Entrez l'année : ");
                JLabel lab1 = new JLabel("Entrez le nom d'une vendeuse et le mois en chiffre!!!");

                //JTextField nom = new JTextField();
                JTextField moi = new JTextField();
                JTextField ane = new JTextField();
                Object[] tab1 = new Object[]{ jMoi, moi, jAne, ane, lab1};

                int pri = 0;
                int som;

                int rep1 = JOptionPane.showOptionDialog(this, tab1, "Information", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

                if (rep1 == JOptionPane.OK_OPTION) {
                    if ( moi.getText().equals("") || ane.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Entrez les information complètes SVP!");
                    } else {
                        String dc = "";

                        if (moi.getText().equals("1") || moi.getText().equals("01")) {
                            dc = "janvier";
                        } else if (moi.getText().equals("2") || moi.getText().equals("02")) {
                            dc = "février";
                        } else if (moi.getText().equals("3") || moi.getText().equals("03")) {
                            dc = "mars";
                        } else if (moi.getText().equals("4") || moi.getText().equals("04")) {
                            dc = "avril";
                        } else if (moi.getText().equals("5") || moi.getText().equals("05")) {
                            dc = "mai";
                        } else if (moi.getText().equals("6") || moi.getText().equals("06")) {
                            dc = "juin";
                        } else if (moi.getText().equals("7") || moi.getText().equals("07")) {
                            dc = "juillet";
                        } else if (moi.getText().equals("8") || moi.getText().equals("08")) {
                            dc = "aoùt";
                        } else if (moi.getText().equals("9") || moi.getText().equals("09")) {
                            dc = "septembre";
                        } else if (moi.getText().equals("10")) {
                            dc = "octobre";
                        } else if (moi.getText().equals("11")) {
                            dc = "novembre";
                        } else if (moi.getText().equals("12")) {
                            dc = "decembre";
                        }
                        rs = db.exécutionQuery("SELECT v.nom_produit,v.prix_vente,v.stock_sortie FROM vente v WHERE v.nom_produit like '%" + txt_no.getText() + "%' and v.id_caisse IN (SELECT id_caisse FROM caisse WHERE jour_vente like '%" + ane.getText() + "-%" + moi.getText() + "-%')");

//                rs = db.exécutionQuery("SELECT v.nom_produit, v.prix_vente,v.stock_sortie,v.id_caisse,caisse.jour_vente,f.prix_unitaire FROM vente v"
//                        + "              Left JOIN caisse on v.id_caisse = caisse.id and caisse.jour_vente like '%" + ane.getText() + "-%" + moi.getText() + "-%'"
//                        + "              Left JOIN on founisseur v.nom_produi=" + txt_no.getText() + " and founisseur.nom_produit= " + txt_no.getText() + "");
                        try {
                            while (rs.next()) {
                                int username1 = rs.getInt("stock_sortie");
                                int username = rs.getInt("prix_vente");

                                som = username - Integer.parseInt(txt_pri.getText());
                                //String password1 = rs.getString("password");
                                //com_rech.addItemListener(username1);
                                //com_rech.setModel(new javax.swing.DefaultComboBoxModel<>(dd username1));
                                pri += som * username1;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        label1.setText(String.valueOf("Le benefice obtenu sur le produit  " + txt_no.getText()   +   "" + "\n" + "" +"" + "" + "au mois de:" + " " + dc + " " + "est de:" + "" + pri + " "));
                        System.out.println("insert into founisseur(id_user,username,) values(" + txt_no.getText() + ",'" + txt_fo.getText() + "')");

                    }
                }
                actualiser();

            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualiser();
        table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_proMouseClicked
        // TODO add your handling code here:
        if (com_rech1.getSelectedItem().equals("choix_action")) {
            JOptionPane.showMessageDialog(this, "Selectionnez une action!!!");
        } else if (com_rech1.getSelectedItem().equals("ajout_prix_achat")) {
            txt_no.setText(String.valueOf(table_pro.getValueAt(table_pro.getSelectedRow(), 0)));
            txt_fo.setText(String.valueOf(table_pro.getValueAt(table_pro.getSelectedRow(), 1)));
        } else {
            txt_no.setText(String.valueOf(table_pro.getValueAt(table_pro.getSelectedRow(), 0)));
            txt_fo.setText(String.valueOf(table_pro.getValueAt(table_pro.getSelectedRow(), 1)));
            txt_pri.setText(String.valueOf(table_pro.getValueAt(table_pro.getSelectedRow(), 3)));
        }

    }//GEN-LAST:event_table_proMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Principale p = new Principale();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void com_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_rechActionPerformed

    private void com_rech1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_rech1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_rech1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(founisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(founisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(founisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(founisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new founisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rech;
    private javax.swing.JComboBox<String> com_rech1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JTable table_pro;
    private javax.swing.JTextField txt_fo;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_pri;
    private javax.swing.JTextField txt_rech;
    // End of variables declaration//GEN-END:variables
}
