/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base_de_donn�e;

/**
 *
 * @author Tchoute
 */
import Application.StatementBd;
import Application.Settings;
import Application.TableModel;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.*;

public class Inventaire extends javax.swing.JFrame {

    
    ResultSet rs;
    StatementBd db;
    Statement statement;
    /**
     * Creates new form Iventaire
     */
    private static Pattern motif=null;
    private static Pattern motif1=null;
    Matcher matcher,matcher1,matcher2;
    
    public Inventaire() {
        db= new StatementBd(new Settings().HOST_DB, new Settings().USERNAME_DB, new 
        Settings().PASSWORD_DB, new Settings().IPHOST, new Settings().PORT);
        initComponents();
        ImageIcon image = new ImageIcon("C:\\Users\\ERIC\\workspace\\Gestion_stock\\bin\\Base_de_donn�e\\Capture_carr�2.png");
        this.setIconImage(image.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_inv = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lab2 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(1000, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        table_inv.setBackground(new java.awt.Color(255, 255, 153));
        table_inv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        table_inv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        table_inv.setForeground(new java.awt.Color(0, 102, 102));
        table_inv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom caisse", "Nom client", "Frais � payer", "Frais payer", "Payer apr�s", "Jour de vente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_inv);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 10, 760, 230);

        jButton5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setText("infos sur un utilisateur ");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 5, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(260, 260, 260, 50);

        jButton7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 153));
        jButton7.setText("Fermer");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 5, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(560, 260, 140, 50);

        jLabel1.setText("ENTERPRISE  tel: (+237) 675692431.  Email: tomiyems@gmail.com");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 320, 450, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 770, 350);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Ventes d une caisse"); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 200, 210, 40);

        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Sur toutes  les ventes");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 50, 210, 40);

        jButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 102));
        jButton3.setText("Sur la vente d un mois");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 100, 210, 40);

        jButton4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 102));
        jButton4.setText("Sur la vente d'un jour");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 150, 210, 40);

        jButton6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 153));
        jButton6.setText("Retour");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 5, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(30, 260, 180, 50);

        jButton8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 102));
        jButton8.setText(" le stock des produits");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 1, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(10, 0, 210, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(760, 80, 240, 350);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        lab2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lab2.setForeground(new java.awt.Color(51, 255, 51));
        jPanel3.add(lab2);
        lab2.setBounds(520, 10, 190, 50);

        lab3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lab3.setForeground(new java.awt.Color(51, 255, 51));
        jPanel3.add(lab3);
        lab3.setBounds(10, 30, 980, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 80);

        pack();
    }// </editor-fold>                        
        //inventaire sur la vente effectu�e par une caisse
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        motif= Pattern.compile("([0-9]*)");
        
        
        JLabel jNom=new JLabel("Nom de la caisse : ");
        JLabel jMoi=new JLabel("Entrez le mois : ");
        JLabel jAne=new JLabel("Entrez l'ann�e : ");
        JLabel lab1=new JLabel("Entrez le nom d'une vendeuse,le mois et l'ann�e en chiffre!!!");
        JTextField nom= new JTextField();
        JTextField moi= new JTextField();
        JTextField ane= new JTextField();
        Object [] tab1= new Object[]{jNom,nom,jMoi,moi,jAne,ane,lab1};
        String id=String.valueOf(moi.getText());
        matcher1= motif.matcher(id);
        
        int rep1= JOptionPane.showOptionDialog(this,tab1,"Informations pour la caisse",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null);
        if(rep1==JOptionPane.OK_OPTION){
             if(nom.getText().equals("") || moi.getText().equals("") || ane.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Entrez les information compl�tes SVP!");
            }else if(!(matcher1.matches())){
                 JOptionPane.showMessageDialog(this,"SVP entrer les chiffres au niveau du mois!!!");
            }
            else{
                 
                  String dc="";
                       if(moi.getText().equals("1") || moi.getText().equals("01")){
                           dc= "Janvier";
                       }
                       else if(moi.getText().equals("2") || moi.getText().equals("02")){
                           dc= "F�vrier";
                       }
                       else if(moi.getText().equals("3") || moi.getText().equals("03")){
                           dc= "Mars";
                       }
                       else if(moi.getText().equals("4") || moi.getText().equals("04")){
                           dc= "Avril";
                       }
                       else if(moi.getText().equals("5") || moi.getText().equals("05")){
                           dc= "Mai";
                       }
                       else if(moi.getText().equals("6") || moi.getText().equals("06")){
                           dc= "Juin";
                       }
                       else if(moi.getText().equals("7") || moi.getText().equals("07")){
                           dc= "Juillet";
                       }
                       else if(moi.getText().equals("8") || moi.getText().equals("08")){
                           dc= "Ao�t";
                       }
                       else if(moi.getText().equals("9") || moi.getText().equals("09")){
                           dc= "Septembre";
                       }
                       else if(moi.getText().equals("10")){
                           dc= "Octobre";
                       }
                       else if(moi.getText().equals("11")){
                           dc= "Novembre";
                       }
                       else if(moi.getText().equals("12")){
                           dc= "Decembre";
                       }
               String invoic =nom.getText().replace(" ","");
               rs=db.ex�cutionQuery("SELECT sexe as subtotal FROM utilisateur WHERE username ="+"'"+ invoic+"'" );
               try{

               rs.afterLast();
               while(rs.previous()){
                    String d= rs.getString("subtotal");
                        if(d.equals("Feminin")){
                        String n="madame";
                        lab2.setText(String.valueOf(""));
                        lab3.setText(String.valueOf("Inventaire sur les ventes effectu�es par  " +n+ " " +nom.getText() +" au cours du mois de  " +dc));
                        rs=db.ex�cutionQuery("SELECT nom_caisse,nom_client,frais_total ,cash ,payer_apr�s ,jour_vente as jour FROM caisse WHERE jour_vente like '%"+ane.getText()+"-%"+moi.getText()+"-%' AND nom_caisse like '%"+nom.getText()+"%' ");
                        table_inv.setModel(new TableModel(rs));
                        }
                        else{
                            String n="monsieur";
                            lab2.setText(String.valueOf(""));
                            lab3.setText(String.valueOf("Inventaire sur les ventes effectu�es par  "  +n+ " "  +nom.getText() +" au cours du mois de  " +dc));
                            rs=db.ex�cutionQuery("SELECT nom_caisse,nom_client,frais_total ,cash ,payer_apr�s ,jour_vente as jour FROM caisse WHERE jour_vente like '%-%"+moi.getText()+"-%' AND nom_caisse like '%"+nom.getText()+"%' ");
                            table_inv.setModel(new TableModel(rs));
                        }
                    
                    
               }
               
               
               }catch(SQLException ex){
                        Logger.getLogger(Caisse.class.getName()).log(Level.SEVERE,null,ex);}


            }
        }
        else{return;}
    }                                        
     //inventaire de toutes les ventes
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        lab2.setText(String.valueOf(""));
        lab3.setText(String.valueOf("Inventaire sur toutes les ventes effectu�es!"));
        String a[]={"nom_produit","prix_vente","stock_sortie","subtotal"};
        rs=db.querySelect(a,"vente");
        table_inv.setModel(new TableModel(rs));
    }                                        
        //inventaire sur les ventes d'un mois donn�
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        JLabel jNum=new JLabel("Un mois de l'ann�e : ");
        JLabel jNum1=new JLabel("Entrer l'ann�e : ");
        JLabel lab1=new JLabel("Entrez Un mois et l'ann�e en chiffre ");
        JTextField mois= new JTextField();
        JTextField ane= new JTextField();
        Object [] tab1= new Object[]{jNum,mois,jNum1,ane,lab1};
       /* motif= Pattern.compile("([0-9]*)");
        String ad=String.valueOf(mois.getText());
        matcher1= motif.matcher(ad);*/
        
        int rep1= JOptionPane.showOptionDialog(this,tab1,"Information pour le mois",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null);
        if(rep1==JOptionPane.OK_OPTION){
            
            if(mois.getText().equals("") || ane.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Entrez les informations compl�tes en chiffre");
            }/*else if( !(matcher1.matches())){
                 JOptionPane.showMessageDialog(this,"SVP entrer les chiffres au niveau du champs  mois de l'ann�e!!!");
            }*/
            else{
                String dc ="";
                
                       if(mois.getText().equals("1") || mois.getText().equals("01")){
                           dc= "Janvier";
                       }
                       else if(mois.getText().equals("2") || mois.getText().equals("02")){
                           dc= "F�vrier";
                       }
                       else if(mois.getText().equals("3") || mois.getText().equals("03")){
                           dc= "Mars";
                       }
                       else if(mois.getText().equals("4") || mois.getText().equals("04")){
                           dc= "Avril";
                       }
                       else if(mois.getText().equals("5") || mois.getText().equals("05")){
                           dc= "Mai";
                       }
                       else if(mois.getText().equals("6") || mois.getText().equals("06")){
                           dc= "Juin";
                       }
                       else if(mois.getText().equals("7") || mois.getText().equals("07")){
                           dc= "Juillet";
                       }
                       else if(mois.getText().equals("8") || mois.getText().equals("08")){
                           dc= "Ao�t";
                       }
                       else if(mois.getText().equals("9") || mois.getText().equals("09")){
                           dc= "Septembre";
                       }
                       else if(mois.getText().equals("10")){
                           dc= "Octobre";
                       }
                       else if(mois.getText().equals("11")){
                           dc= "Novembre";
                       }
                       else if(mois.getText().equals("12")){
                           dc= "Decembre";
                       }
               lab3.setText(String.valueOf("Inventaire sur toutes les ventes du mois de " +dc +" " +ane.getText()));
               rs=db.ex�cutionQuery("SELECT v.nom_produit as pro,v.prix_vente,v.stock_sortie,v.subtotal FROM vente v WHERE v.id_caisse IN (SELECT id_caisse FROM caisse WHERE jour_vente like '%"+ane.getText()+"-%"+mois.getText()+"-%')");
              
                table_inv.setModel(new TableModel(rs));
            }
        }
        else{return;}
        
    }                                        
    //inventaire sur la vente d'un jour donn�
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        JLabel jNum=new JLabel("Jour de la semaine : ");
        JLabel jMoi=new JLabel("Entrez le mois : ");
        JLabel jAne=new JLabel("Entrez l'ann�e : ");
        JLabel lab1=new JLabel("Entrez un jour de la semaine et le mois en chiffre!!!");
        JTextField num= new JTextField();
        JTextField moi= new JTextField();
        JTextField ane= new JTextField();
        Object [] tab1= new Object[]{jNum,num,jMoi,moi,jAne,ane,lab1};
       /* motif= Pattern.compile("([0-9]*)");
        String ad=String.valueOf(moi.getText());
        String d=String.valueOf(num.getText());
        String idd=String.valueOf(ane.getText());
        matcher1= motif.matcher(ad);
        matcher= motif.matcher(d);
        matcher2= motif.matcher(idd);*/
        
        int rep1= JOptionPane.showOptionDialog(this,tab1,"Information du jour",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,null,null);
        if(rep1==JOptionPane.OK_OPTION){
            
            if(num.getText().equals("") || moi.getText().equals("") || ane.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Entrez les informations compl�tes");
            }/*else if(!(matcher.matches()) || !(matcher1.matches()) || !(matcher2.matches())){
                 JOptionPane.showMessageDialog(this,"SVP entrer les chiffres au niveau des champs jour de la semaine; mois et ann�e!!!");
            }*/
            else{
                
                 //rs=db.ex�cutionQuery("SELECT jour_vente as subtotal FROM caisse WHERE jour_vente like '%-%-%"+num.getText()+"'");
                 

                 
                 
                       lab1.setText(String.valueOf(""));
                       lab3.setText(String.valueOf("Inventaire sur toutes les ventes du " +num.getText() +"/" +moi.getText() +"/" +ane.getText()));

                       
                       //lab2.setText(String.valueOf(dc));
                   
                rs=db.ex�cutionQuery("SELECT v.nom_produit,v.prix_vente,v.stock_sortie,v.subtotal FROM vente v WHERE v.id_caisse IN (SELECT id_caisse FROM caisse WHERE jour_vente like '%"+ane.getText()+"-%"+moi.getText()+"-%"+num.getText()+"')");
                table_inv.setModel(new TableModel(rs));
                String id=String.valueOf(table_inv.getValueAt(table_inv.getSelectedRow(),0));
                if(id.equals("")){
                    JOptionPane.showMessageDialog(this, "Aucun!!!");
                }

            }
        }
        else{return;}
    }                                        
     //Fermer
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        dispose();
    }                                        
     //Retour
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        Admin p= new Admin();
        p.setVisible(true);
        this.dispose();
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        lab2.setText(String.valueOf(""));
        lab3.setText(String.valueOf("Inventaire sur tous les produits pr�sent en stock!"));
        String a[]={"code_produit","nom_produit","fournisseur","remise","prix","stock"};
        rs=db.querySelect(a,"produit");
        table_inv.setModel(new TableModel(rs));
    }                                        
     //bouton information sur un utilisateur
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        Utilisateur u = new Utilisateur();
        u.setVisible(true);
        this.dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JTable table_inv;
    // End of variables declaration                   
}

