/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_donnée;

import java.text.SimpleDateFormat;
import java.util.Date;
import Application.BDD;
import Application.Parameter;
import de.javasoft.plaf.synthetica.SyntheticaLookAndFeel;
import static java.awt.PageAttributes.MediaType.C;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Roger
 */
public class Login extends javax.swing.JFrame {
    //déclaration
    ResultSet rs;
    BDD db;
    String username1, password1, hak;
    public static String UIMANAGER_STRING="de.javasoft.plaf.synthetica.SyntheticaLookAndFeel";
    /**
     * Creates new form Login
     */
    public Login() {
        db=new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, 
                new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT); 
        initComponents();
        ImageIcon image = new ImageIcon("C:\\Users\\Roger\\Pictures\\CAPTURE\\Capture_carré.png");
this.setIconImage(image.getImage());
        
        changeLookandFeel();
        
    }
    
    public void jam(){
        long s = 0;
        Date date = new Date();
        SimpleDateFormat tgl= new SimpleDateFormat("YYYY-MM-dd");
        SimpleDateFormat jam= new SimpleDateFormat("HH:mm:ss");
        jam.format(date);
        
        tgl.format(date);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        setForeground(new java.awt.Color(0, 255, 255));
        setLocation(new java.awt.Point(510, 220));
        setPreferredSize(new java.awt.Dimension(383, 335));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 90, 30);

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username);
        txt_username.setBounds(150, 100, 120, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Fermé");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 240, 100, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 240, 100, 40);

        jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(jlabel);
        jlabel.setBounds(150, 140, 140, 0);

        pass.setText("jPasswordField1");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(150, 170, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel4.setText("MICROSOFT ENTERPRISE. tel:675692431. tomiyems@gmail.com");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 290, 350, 14);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 20, 138, 56);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jButton2.setSelected(true);
        
       /* rs = db.querySelectAll("utilisateur","username="+txt_username.getText()
                + " and password="+txt_password.getText()+"");
        System.out.print(rs);
        try {
            rs.beforeFirst();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }*/
       rs=db.exécutionQuery("select * from utilisateur where username= '" +txt_username.getText()+"'and password= '" +pass.getText()+"'");
       System.out.print(rs);
        try {
            rs.beforeFirst();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
           while(rs.next()){
               username1= rs.getString("username");
               password1=rs.getString("password");
               hak=rs.getString("fonction");
               System.out.print(username1);
           }
        }catch(SQLException ex){
           Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
        if(username1==null && password1==null){
           JOptionPane.showMessageDialog(this,"le nom de l'utilisateur ou le mots de pass est incorect");
           jlabel.setText("erreuuuuuuuuuur");
           jlabel.setVisible(true);
        }else{
           if(hak.equals("Directeur")){
               Principale h= new Principale();
               h.setVisible(true);
               this.dispose();
           }else if(hak.equals("Magasinier")){
               Produit k= new Produit();
               k.setVisible(true);
               this.dispose();
           }
           else {
               Cachier k= new Cachier(username1);
               k.setVisible(true);
               this.dispose();
              // String a= String.valueOf("txt_username.getText()");
              // k.labele.setText("Welcom "+a);
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_passActionPerformed
private static void changeLookandFeel() {
        try {

            UIManager.removeAuxiliaryLookAndFeel(UIManager.getLookAndFeel());
            SyntheticaLookAndFeel.setWindowsDecorated(false);
            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel");
            //UIManager.setLookAndFeel(UIMANAGER_STRING);

//             for (int i = 0; i < LookAndFeel.getFrames().length; ++i) {
//                SwingUtilities.updateComponentTreeUI(LookAndFeel.getFrames()[i]);
//                SwingUtilities.updateComponentTreeUI(this);
//            }
         //   SwingUtilities.updateComponentTreeUI(this);

        } catch (Exception ex) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
    
                new Login().setVisible(true);
                
            }
            
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
