/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base_de_donnée;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;

import Application.StatementBd;
import Application.Settings;
import de.javasoft.plaf.synthetica.SyntheticaLookAndFeel;
import static java.awt.PageAttributes.MediaType.C;

import java.awt.Image;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Tchoute
 */
public class Login extends javax.swing.JFrame {
    //d�claration
	   ResultSet rs, req;
	    StatementBd db;
	    String username1, password1, hak, nom, etat, enday;
	    //Date enday;
	    public static String UIMANAGER_STRING="de.javasoft.plaf.synthetica.SyntheticaLookAndFeel";
	    /**
	     * Creates new form Login
	     */
	    public Login() {
	        db=new StatementBd(new Settings().HOST_DB, new Settings().USERNAME_DB, 
	                new Settings().PASSWORD_DB, new Settings().IPHOST, new Settings().PORT); 
	        initComponents();
	        ImageIcon image = new ImageIcon("C:\\Users\\ERIC\\workspace\\Gestion_stock\\bin\\Base_de_donn�e\\Capture_carr�2.png");
	        this.setIconImage(image.getImage());
	        changeLookandFeel();
	        
	    }
	    
	    public void jam(){
	        long s = 0;
	        Date date = new Date();
	        SimpleDateFormat tgl= new SimpleDateFormat("YYYY-MM-dd");
	        SimpleDateFormat jam= new SimpleDateFormat("HH:mm:ss");
	        jam.format(date);
	        
	        tgl.format(date);
	      }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        txt_username = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();
	        jButton2 = new javax.swing.JButton();
	        jlabel = new javax.swing.JLabel();
	        pass = new javax.swing.JPasswordField();
	        jPanel1 = new javax.swing.JPanel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel1 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setBackground(new java.awt.Color(0, 102, 102));
	        setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
	        setForeground(new java.awt.Color(0, 255, 255));
	        setPreferredSize(new java.awt.Dimension(383, 335));
	        setResizable(false);
	        getContentPane().setLayout(null);
	        
	        

	        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel2.setText("password:");
	        getContentPane().add(jLabel2);
	        jLabel2.setBounds(40, 170, 90, 30);

	        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel3.setText("username:");
	        getContentPane().add(jLabel3);
	        jLabel3.setBounds(40, 100, 90, 30);

	        txt_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        txt_username.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                txt_usernameActionPerformed(evt);
	            }
	        });
	        getContentPane().add(txt_username);
	        txt_username.setBounds(150, 100, 120, 30);

	        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
	        jButton1.setText("Ferm�");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });
	        getContentPane().add(jButton1);
	        jButton1.setBounds(230, 240, 100, 40);

	        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
	        jButton2.setText("Login");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	
					jButton2ActionPerformed(evt);
					
	            }
	        });
	        getContentPane().add(jButton2);
	        jButton2.setBounds(30, 240, 100, 40);

	        jlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	        jlabel.setForeground(new java.awt.Color(255, 0, 102));
	        getContentPane().add(jlabel);
	        jlabel.setBounds(150, 140, 140, 0);

	        pass.setText("jPasswordField1");
	        pass.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                passActionPerformed(evt);
	            }
	        });
	        getContentPane().add(pass);
	        pass.setBounds(150, 170, 120, 30);

	        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
	        jPanel1.setLayout(null);

	        jLabel4.setText("ENTERPRISE tel:(+237)675692431 tomiyems@gmail.com");
	        jPanel1.add(jLabel4);
	        jLabel4.setBounds(20, 290, 350, 14);

	        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
	        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
	        jLabel1.setText("Login");
	        jPanel1.add(jLabel1);
	        jLabel1.setBounds(110, 20, 138, 56);

	        getContentPane().add(jPanel1);
	        jPanel1.setBounds(0, 0, 380, 310);

	        pack();
	    }// </editor-fold>                        

	    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        // 
	    }                                            
        // Fermeture
	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        
	        dispose();
	    }                                        
        // Login
	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)  {                                         
	        int virus1=0;
	        LocalDate date2 = null;
	    	Date dat1   = new Date();
	    	Date  dat  = new Date();
	    	java.sql.Date sqlDate = null, sqlDate1 = null;
	        SimpleDateFormat tgl= new SimpleDateFormat("YYYY-MM-dd");
	        
	        Calendar c = new GregorianCalendar(); //recup�re la date du jour actuelle
	        
	        String d = tgl.format(c.getTime()); // affiche la date actuelle
	        
	        LocalDate date = LocalDate.parse(d, DateTimeFormatter.ISO_DATE);
	        //LocalDate date1 = LocalDate.parse(d, DateTimeFormatter.BASIC_ISO_DATE);
	        //Instant dat11 = Instant.parse(d);
	        //LocalDateTime result = LocalDateTime.ofInstant(dat11, ZoneId.of(ZoneOffset.UTC.getId()));

	        System.out.println("la nouvelle date est : "+date);
	        jButton2.setSelected(true);
	        
	       /* rs = db.querySelectAll("utilisateur","username="+txt_username.getText()
	                + " and password="+txt_password.getText()+"");
	        System.out.print(rs);
	        try {
	            rs.beforeFirst();
	        } catch (SQLException ex) {
	            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
	        }*/
	        
	       
	        
	       rs=db.exécutionQuery("select * from utilisateur where username= '" +txt_username.getText()+"'and password= '" +pass.getText()+"'");
	       System.out.print(rs);
	        try {
	            rs.beforeFirst();
	        } catch (SQLException ex) {
	            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
	        }
	        try{
	           while(rs.next()){
	               username1= rs.getString("username");
	               password1=rs.getString("password");
	               nom = rs.getString("entreprise");
	               hak=rs.getString("fonction");
	               System.out.print(username1);
	           }
	        }catch(SQLException ex){
	           Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
	        }
	        
	        req=db.exécutionQuery("select * from entreprise where nom_entreprise = '"+nom+"'");
	        try{
	        	while(req.next()){
	        		if (!hak.equals("administrateur")){
	        	         enday = req.getString("date_fin_licence");
	        	         etat = req.getString("statu_entreprise");
	        	         date2 = LocalDate.parse(enday, DateTimeFormatter.ISO_DATE);
	        		}
	        	
	        	}
	        }catch(SQLException ex){
		           Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
		    }
	        
	        //LocalDate date2 = LocalDate.parse(enday, DateTimeFormatter.ISO_DATE);
	        System.out.println("la date de la bd nouvelle ++ est: "+date2);
	        if((username1==null && password1==null)){
	           JOptionPane.showMessageDialog(this,"le nom de l'utilisateur ou le mots de pass est incorect");
	           jlabel.setText("erreuuuuuuuuuur");
	           jlabel.setVisible(true);
	        }
	        
	        else if (!hak.equals("administrateur") && (date.isAfter(date2))){ 
	        	//LocalDate date2 = LocalDate.parse(enday, DateTimeFormatter.ISO_DATE);
	        	//if(date.isAfter(date2)){
   		            //System.out.println("la date de la bd nouvelle ++ est: "+date2);
	        	    JOptionPane.showMessageDialog(this," Votre licence est arriv�e � expiration. Veuillez l'a renouveller aupr�s de votre fournisseur.");
	    
	        	//}
	        }
	        else{
	           if(hak.equals("Directeur")){
	               Principale h= new Principale();
	               h.setVisible(true);
	               this.dispose();
	           }else if(hak.equals("Magasinier")){
	               Produit k= new Produit();
	               k.setVisible(true);
	               this.dispose();
	           }else if(hak.equals("administrateur")){
	               Droit k= new Droit();
	               k.setVisible(true);
	               this.dispose();
	           }
	           else {
	               Caisse k= new Caisse(username1);
	               k.setVisible(true);
	               this.dispose();
	              // String a= String.valueOf("txt_username.getText()");
	              // k.labele.setText("Welcom "+a);
	           }
	        }
	    }                                        

	    private void passActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // 
	       
	        
	    }                                    
	private static void changeLookandFeel() {
	        try {

	            UIManager.removeAuxiliaryLookAndFeel(UIManager.getLookAndFeel());
	            SyntheticaLookAndFeel.setWindowsDecorated(false);
	            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel");
	            //UIManager.setLookAndFeel(UIMANAGER_STRING);

//	             for (int i = 0; i < LookAndFeel.getFrames().length; ++i) {
//	                SwingUtilities.updateComponentTreeUI(LookAndFeel.getFrames()[i]);
//	                SwingUtilities.updateComponentTreeUI(this);
//	            }
	         //   SwingUtilities.updateComponentTreeUI(this);

	        } catch (Exception ex) {
	            try {
	                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
	            } catch (Exception e) {
	                e.printStackTrace();
	            }
	        }
	    }


	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        
	        

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	            	//this.setIconImage(new ImageIcon("image.gif")); \
	            	Image logosa =  new javax.swing.ImageIcon("C:\\Users\\ERIC\\workspace\\Gestion_stock\\bin\\Base_de_donn�e\\Capture_carr�2.png").getImage();
	            	new Login().setIconImage(logosa);
	                new Login().setVisible(true);
	                
	            }
	            
	        });
	        
	    }
	    

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JLabel jlabel;
	    private javax.swing.JPasswordField pass;
	    private javax.swing.JTextField txt_username;
	    // End of variables declaration                   
	}

