/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_donnée;


import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.*;

/**
 *
 * @author Roger
 */
public class Recu extends javax.swing.JFrame {

    ResultSet rs;
    BDD db;
    Cachier c= new Cachier();
    /**
     * Creates new form Recu
     */
    public Recu() {
        
        db= new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new 
        Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        importer();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_re = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        blpay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        blh = new javax.swing.JLabel();
        blto = new javax.swing.JLabel();
        blcas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bld = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 370));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 340));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setText("Reçu");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 10, 100, 40);

        table_re.setBackground(new java.awt.Color(255, 255, 204));
        table_re.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 3, true));
        table_re.setForeground(new java.awt.Color(102, 51, 255));
        table_re.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "nom_produit", "prix_vente", "stock_sortie", "subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_re);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 90, 550, 100);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 270, 110, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(50, 220, 110, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Payé après:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 280, 120, 30);

        blpay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        blpay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blpay.setText("XX");
        blpay.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(blpay);
        blpay.setBounds(370, 280, 140, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Cash:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 240, 100, 30);

        blh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(blh);
        blh.setBounds(320, 50, 250, 30);

        blto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        blto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blto.setText("XX");
        jPanel1.add(blto);
        blto.setBounds(370, 200, 140, 30);

        blcas.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        blcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blcas.setText("XX");
        blcas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(blcas);
        blcas.setBounds(370, 240, 140, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Total:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 200, 100, 30);

        bld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(bld);
        bld.setBounds(20, 50, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cachier d= new Cachier();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.printComponents(null);
    }//GEN-LAST:event_jButton2ActionPerformed

        public void importer(){
        
       String colon []={"num_facture","code_produit","nom_produit","prix_vente","stock_sortie","subtotal"};
       rs= db.fcSelectCommand(colon, "vente", "num_facture = '" +c.getTxt_fac()+ "' ");
       table_re.setModel(new ResultSetTableModel(rs));
       int a= Integer.parseInt(c.getJbito2());
       blto.setText(c.getJbito2());
       blcas.setText(c.getTxt_cas());
       //payaprès();
       System.out.println(a);
        
    }
    
    public void date(){
       bld.setText(c.getBit6());
       blh.setText(c.getBit4());
    }
   
    
    public void payaprès(){
       int a= Integer.parseInt(String.valueOf(c.getJbito2()));
       int b= Integer.parseInt(String.valueOf(c.getTxt_cas()));
       int cd = b-a;
       blpay.setText(Integer.toString(cd));
      
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blcas;
    private javax.swing.JLabel bld;
    private javax.swing.JLabel blh;
    private javax.swing.JLabel blpay;
    private javax.swing.JLabel blto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_re;
    // End of variables declaration//GEN-END:variables
}
